version: '3.8'

services:
  admin-backend:
    build:
      context: ./admin/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./admin/backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/weduca-admin
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb

  client-backend:
    build:
      context: ./client/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/backend:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/weduca-client
      - CORS_ORIGIN=http://localhost:5174
    depends_on:
      - mongodb

  admin-frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./admin/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

  client-frontend:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/frontend:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=http://localhost:8081

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 