services:
  # Admin Backend Service
  - type: web
    name: weduca-admin-backend
    env: docker
    region: frankfurt
    dockerfilePath: ./admin/backend/Dockerfile
    dockerContext: ./admin/backend
    buildCommand: npm ci --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://weduca-admin-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

  # Admin Frontend Service
  - type: web
    name: weduca-admin-frontend
    env: static
    buildCommand: cd admin/frontend && npm install && npm run build
    staticPublishPath: ./admin/frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://weduca-admin-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Client Backend Service
  - type: web
    name: weduca-client-backend
    env: docker
    region: frankfurt
    dockerfilePath: ./client/backend/Dockerfile
    dockerContext: ./client/backend
    buildCommand: npm ci --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://weduca-client-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

  # Client Frontend Service
  - type: web
    name: weduca-client-frontend
    env: node
    buildCommand: cd client/frontend && npm install && npm run build
    startCommand: mpx serve -s ./client/frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://weduca-client-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 