services:
  # Admin Backend Service
  - type: web
    name: weduca-admin-backend
    env: node
    region: frankfurt  # You can change this to your preferred region
    buildCommand: cd admin/backend && npm install
    startCommand: cd admin/backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # This will be set manually in Render dashboard
      - key: PORT
        value: 8080
    healthCheckPath: /api/health
    autoDeploy: true

  # Admin Frontend Service
  - type: web
    name: weduca-admin-frontend
    env: static
    buildCommand: cd admin/frontend && npm install && npm run build
    staticPublishPath: admin/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://weduca-admin-backend.onrender.com  # Update this with your actual backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Client Backend Service
  - type: web
    name: weduca-client-backend
    env: node
    region: frankfurt
    buildCommand: cd client/backend && npm install
    startCommand: cd client/backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # This will be set manually in Render dashboard
      - key: PORT
        value: 8080
    healthCheckPath: /api/health
    autoDeploy: true

  # Client Frontend Service
  - type: web
    name: weduca-client-frontend
    env: static
    buildCommand: cd client/frontend && npm install && npm run build
    staticPublishPath: client/frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://weduca-client-backend.onrender.com  # Update this with your actual backend URL
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 